import {Project} from "./project";

export const PROJECTS: Project[] = [
    {
        id: 2,
        name: "Reddcoin Browser Wallet",
        templateUrl : "../assets/templates/reddcoin.html",
        description : "My most technically challenging project to date was building a Crypto-Currency wallet " +
        "with Node and Browserify.",
        background : "/assets/images/reddcoin.jpg",
        code : "https://github.com/reddcoin-project/reddcoin-electrum-js",
        link : "Link Unavailable",
        status : "Deprecated",
        tags : ["Javascript", "Node", "Blockchain", "Browser Extension"],
    },
    {
        id: 1,
        name: "Writing Samples",
        templateUrl : "../assets/templates/writing.html",
        description : "When deciding to bring someone onto your team, it's important that they're " +
        "technically competent, but it's also important that they can communicate effectively.",
        background : '/assets/images/writing.svg',
        code : "https://github.com/agroff/agroff.github.io/tree/master/posv",
        link : "http://agroff.github.io/posv/",
        status : "Not Applicable",
        tags : ["Writing", "Communication"],
    },
    {
        id: 3,
        name: "BitSurv",
        templateUrl : "../assets/templates/writing.html",
        description : "BitSurv is a side project I started in an effort to replace a tool we used at work to build surveys.",
        background : "/assets/images/bitsurv.png",
        code : "https://github.com/agroff/bitsurv",
        link : "Link Unavailable",
        status : "Production",
        tags : ["PHP"],
    },
    {
        id: 4,
        name: "Kitty Helper",
        templateUrl : "../assets/templates/writing.html",
        description : "Shortly after the launch of CryptoKitties (short-lived block-chain beanie babies), I made this extension to upgrade the site's interface.",
        background : "/assets/images/kitty-helper.png",
        code : "https://github.com/agroff/kitty-helper",
        link : "https://chrome.google.com/webstore/detail/kitty-helper/dceabgpbnaimhibdgjdhgbabiocgimhb?hl=en-US",
        status : "Deprecated",
        tags : ["Javascript", "Browser Extension", "Blockchain"],
    },
    {
        id: 10,
        name: "Portfolio",
        templateUrl : "../assets/templates/writing.html",
        description : "You're looking at this project right now. This portfolio was my first foray into typescript and Angular 6",
        background : "/assets/images/portfolio.png",
        code : "https://github.com/agroff/groff.cc",
        link : "https://groff.cc/",
        status : "Production",
        tags : ["Angular", "Typescript"],
    },
    {
        id: 13,
        name: "Cash Out on Dip",
        templateUrl : "../assets/templates/writing.html",
        description : "Cash out on dip is a model project at Rescue. It was built inexpensively and managed to get more engagement per dollar than any other project.",
        background : "/assets/images/cashoutondip.jpg",
        code : "http://downanddirtylife.com/cashoutondip/js/game.js",
        link : "http://downanddirtylife.com/cashoutondip/",
        status : "Production",
        tags : ["Javascript", "Phaser"],
    },
    {
        id: 6,
        name: ".rescue",
        templateUrl : "../assets/templates/writing.html",
        description : ".rescue is a CLI tool powered by Vagrant ",
        background : "/assets/images/rescue.png",
        code : "",
        link : "",
        status : "",
        tags : ["PHP", "Vagrant", "CLI", "Linux"],
    },
    {
        id: 5,
        name: "This Free Life",
        templateUrl : "../assets/templates/writing.html",
        description : "This Free Life is an LGBT focused public health campaign written in AngularJs and powered by a Drupal 8 API.",
        background : "/assets/images/this-free-life.jpg",
        code : "Proprietary",
        link : "https://thisfreelife.betobaccofree.hhs.gov/",
        status : "Production",
        tags : ["Angular", "Javascript", "Drupal"],
    },
    {
        id: 7,
        name: "Rescue.FYI",
        templateUrl : "../assets/templates/writing.html",
        description : "",
        background : "/assets/images/rescue-fyi.png",
        code : "",
        link : "",
        status : "",
        tags : [],
    },
    {
        id: 8,
        name: "TeamView",
        templateUrl : "../assets/templates/writing.html",
        description : "",
        background : "",
        code : "",
        link : "",
        status : "",
        tags : [],
    },
    {
        id: 9,
        name: "Groff/Command",
        templateUrl : "../assets/templates/writing.html",
        description : "",
        background : "",
        code : "",
        link : "",
        status : "",
        tags : [],
    },

    {
        id: 11,
        name: "Pokemon Quest Guide",
        templateUrl : "../assets/templates/writing.html",
        description : "",
        background : "",
        code : "",
        link : "",
        status : "",
        tags : [],
    },
    {
        id: 12,
        name: "Flewent",
        templateUrl : "../assets/templates/writing.html",
        description : "",
        background : "",
        code : "",
        link : "",
        status : "",
        tags : [],
    }
];
